<?php
/**
 * @link        http://www.phpcorner.net
 * @author      qingbing<780042175@qq.com>
 * @copyright   Chengdu Qb Technology Co., Ltd.
 */

namespace YiiConfigureManage\block\services;

use Exception;
use yii\base\Action;
use yii\db\StaleObjectException;
use YiiConfigureManage\block\interfaces\IBlockOptionService;
use YiiConfigureManage\block\models\BlockCategory;
use YiiConfigureManage\block\models\BlockOption;
use YiiHelper\abstracts\Service;
use YiiHelper\helpers\AppHelper;
use Zf\Helper\Exceptions\BusinessException;

/**
 * 服务: 区块选项管理
 *
 * Class BlockOptionService
 * @package YiiConfigureManage\block\services
 */
class BlockOptionService extends Service implements IBlockOptionService
{
    /**
     * @var BlockCategory
     */
    protected $category;

    /**
     * 在action前统一执行
     *
     * @param Action|null $action
     * @return bool
     * @throws Exception
     */
    public function beforeAction(Action $action = null)
    {
        $this->category = BlockCategory::findOne([
            'key' => $action->controller->getParam('key', null),
        ]);
        if (null === $this->category) {
            throw new BusinessException("不存在的区块类型");
        }
        if (in_array($this->category->type, [
            BlockCategory::TYPE_CONTENT,
            BlockCategory::TYPE_IMAGE,
            BlockCategory::TYPE_IMAGE_LINK,
        ])) {
            throw new BusinessException("区块({$this->category->name})不能设置子选项");
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * 区块选项列表
     *
     * @param array|null $params
     * @return array
     */
    public function list(array $params = []): array
    {
        return $this->category->options;
    }

    /**
     * 添加区块选项
     *
     * @param array $params
     * @return bool
     * @throws BusinessException
     * @throws \yii\db\Exception
     */
    public function add(array $params): bool
    {
        $model = new BlockOption();
        $model->setFilterAttributes($params);
        return $model->saveOrException();
    }

    /**
     * 编辑区块选项
     *
     * @param array $params
     * @return bool
     * @throws BusinessException
     * @throws \yii\db\Exception
     */
    public function edit(array $params): bool
    {
        $model = $this->getModel($params);
        unset($params['id'], $params['key']);
        $model->setFilterAttributes($params);
        return $model->saveOrException();
    }

    /**
     * 删除区块选项
     *
     * @param array $params
     * @return bool
     * @throws BusinessException
     * @throws \Throwable
     * @throws StaleObjectException
     */
    public function del(array $params): bool
    {
        return $this->getModel($params)->delete();
    }

    /**
     * 查看区块选项详情
     *
     * @param array $params
     * @return mixed|BlockOption
     * @throws BusinessException
     */
    public function view(array $params)
    {
        return $this->getModel($params);
    }

    /**
     * 获取当前操作模型
     *
     * @param array $params
     * @return BlockOption
     * @throws BusinessException
     */
    protected function getModel(array $params): BlockOption
    {
        $model = BlockOption::findOne([
            'id'  => $params['id'] ?? null,
            'key' => $params['key'] ?? null,
        ]);
        if (null === $model) {
            throw new BusinessException("区块选项不存在");
        }
        return $model;
    }

    /**
     * 刷新区块中选项排序
     *
     * @param array $params
     * @return bool
     * @throws \Throwable
     */
    public function refreshOrder(array $params): bool
    {
        $options = $this->category->options;
        AppHelper::app()->getDb()->transaction(function () use ($options) {
            $sort_order = 1;
            foreach ($options as $option) {
                $option->sort_order = $sort_order++;
                $option->saveOrException();
            }
        });
        return true;
    }

    /**
     * 上移选项顺序
     *
     * @param array $params
     * @return bool
     * @throws BusinessException
     * @throws \Throwable
     */
    public function orderUp(array $params): bool
    {
        // 当前模型
        $model = $this->getModel($params);
        // 获取上一顺序模型
        $prevModel = $this->getBrother($model, PREV);
        // 交换 sort_order
        return $this->switchSortOrder($model, $prevModel);
    }

    /**
     * 下移选项顺序
     *
     * @param array $params
     * @return bool
     * @throws BusinessException
     * @throws \Throwable
     */
    public function orderDown(array $params): bool
    {
        // 当前模型
        $model = $this->getModel($params);
        // 获取上一顺序模型
        $nextModel = $this->getBrother($model, NEXT);
        // 交换 sort_order
        return $this->switchSortOrder($model, $nextModel);
    }

    /**
     * 交换两个模型的 sort_order
     *
     * @param BlockOption $sourceModel
     * @param BlockOption $targetModel
     * @return bool
     * @throws \Throwable
     */
    protected function switchSortOrder(BlockOption $sourceModel, ?BlockOption $targetModel)
    {
        AppHelper::app()->getDb()->transaction(function () use ($sourceModel, $targetModel) {
            if (null === $targetModel) {
                return;
            }
            $sort_order              = $sourceModel->sort_order;
            $sourceModel->sort_order = $targetModel->sort_order;
            $sourceModel->saveOrException();

            $targetModel->sort_order = $sort_order;
            $targetModel->saveOrException();
        });
        return true;
    }

    /**
     * 获取对调的兄弟模型
     *
     * @param BlockOption $model
     * @param string $type
     * @return array|BlockOption|null
     */
    protected function getBrother(BlockOption $model, string $type)
    {
        $differs = [
            PREV => ['oper' => '<', 'sort' => 'sort_order DESC'],
            NEXT => ['oper' => '>', 'sort' => 'sort_order ASC'],
        ];
        return BlockOption::find()
            ->andWhere(['=', 'key', $model->key])
            ->andWhere([$differs[$type]['oper'], 'sort_order', $model->sort_order])
            ->orderBy($differs[$type]['sort'])
            ->one();
    }
}